
server:
  error:
    include-message: always
    include-binding-errors: always
mpesa:
  daraja:
    consumer-key: W0pmY712MVuTuxTcu6JqHJ4fEJwWCZwk
    consumer-secret: mcLoGXtoNGVtSNuC
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl #https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate #https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode:  683024 #603021
    confirmationURL: https://85cc-105-161-109-5.eu.ngrok.io/mobile-money/confirmation
    validationURL: https://85cc-105-161-109-5.eu.ngrok.io/mobile-money/validation
    responseType: Completed
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://85cc-105-161-109-5.eu.ngrok.io/mobile-money/transaction-result
    b2c-queue-timeout-url: https://adf94cda8cd2.ngrok.io/mobile-money/b2c-queue-timeout
    b2c-initiator-name: apiop37
    b2c-initiator-password: Safaricom3021#
    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
    checkAccountBalanceUrl: https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query
    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    stkPushShortCode: 174379
    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkPushRequestCallbackUrl: https://85cc-105-161-109-5.eu.ngrok.io/mobile-money/stk-transaction-result



spring:
  datasource:
    password: 4e5dc52ee640b2f7c42c98db3baaf9fa9b93d38aec2633ef2f034c9fe528f655
    url: jdbc:postgresql://ec2-34-203-182-65.compute-1.amazonaws.com:5432/d8f3prg3reegbk
    username: pdyjwbwmwzzduq
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:

    host: smtp.gmail.com
    port: 587
    username: benardwamache@gmail.com
    password: mjhpxaqrhtteilyw

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          #connectiontimeout: 5000
          #timeout: 3000
          #writetimeout: 5000
#
##  springdoc:
##    :api-docs:
##      path: /api